output "cluster_id" {
  description = "The ID/name of the EKS cluster"
  value       = aws_eks_cluster.main.id
}

output "cluster_arn" {
  description = "The ARN of the EKS cluster"
  value       = aws_eks_cluster.main.arn
}

output "cluster_endpoint" {
  description = "Endpoint for your EKS Kubernetes API"
  value       = aws_eks_cluster.main.endpoint
}

output "cluster_version" {
  description = "The Kubernetes server version for the cluster"
  value       = aws_eks_cluster.main.version
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = aws_eks_cluster.main.certificate_authority[0].data
  sensitive   = true
}

output "cluster_role_arn" {
  description = "ARN of the cluster IAM role"
  value       = aws_iam_role.cluster.arn
}

output "cluster_role_name" {
  description = "Name of the cluster IAM role"
  value       = aws_iam_role.cluster.name
}

output "node_role_arn" {
  description = "ARN of the node IAM role"
  value       = aws_iam_role.node.arn
}

output "node_role_name" {
  description = "Name of the node IAM role"
  value       = aws_iam_role.node.name
}

output "node_group_ids" {
  description = "EKS node group IDs"
  value       = [for ng in aws_eks_node_group.main : ng.id]
}

output "node_group_arns" {
  description = "EKS node group ARNs"
  value       = [for ng in aws_eks_node_group.main : ng.arn]
}

output "node_group_status" {
  description = "Status of the EKS node groups"
  value       = { for k, ng in aws_eks_node_group.main : k => ng.status }
}

output "security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = try(tolist(aws_eks_cluster.main.vpc_config[0].security_group_ids)[0], null)
}

output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value = base64encode(jsonencode({
    apiVersion      = "v1"
    kind            = "Config"
    current-context = "aws_eks"
    clusters = [{
      name = aws_eks_cluster.main.id
      cluster = {
        certificate-authority-data = aws_eks_cluster.main.certificate_authority[0].data
        server                      = aws_eks_cluster.main.endpoint
      }
    }]
    contexts = [{
      name = "aws_eks"
      context = {
        cluster = aws_eks_cluster.main.id
        user    = "aws_eks"
      }
    }]
    users = [{
      name = "aws_eks"
      user = {
        exec = {
          apiVersion = "client.authentication.k8s.io/v1beta1"
          command    = "aws"
          args       = ["eks", "get-token", "--cluster-name", aws_eks_cluster.main.id, "--region", data.aws_region.current.name]
        }
      }
    }]
  }))
  sensitive = true
}

data "aws_region" "current" {}
